image: python:3.7-alpine

pages:
  stage: deploy
  script:
  - pip install -U sphinx nbsphinx sphinx-rtd-theme recommonmark
  - sphinx-build -b html ./website public
  artifacts:
    paths:
    - public
  only:
  - master
