Input File Manipulation - Macros
--------------------------------

.. currentmodule:: swmm_api.input_file.macros

.. rubric:: Overview

.. autosummary::
    split_inp_to_files
    read_split_inp_file
    combined_subcatchment_frame
    get_node_tags
    get_link_tags
    get_subcatchment_tags
    filter_tags
    nodes_dict
    find_node
    links_dict
    find_link
    calc_slope
    conduit_slopes
    conduits_are_equal
    delete_node
    move_flows
    delete_link
    delete_subcatchment
    split_conduit
    combine_vertices
    combine_conduits
    combine_conduits_keep_slope
    dissolve_conduit
    conduit_iter_over_inp
    junction_to_storage
    junction_to_outfall
    conduit_to_orifice
    subcachtment_nodes_dict
    rename_node
    rename_link
    rename_timeseries
    remove_empty_sections
    reduce_curves
    simplify_curves
    reduce_raingages
    filter_nodes
    filter_links_within_nodes
    filter_links
    filter_subcatchments
    update_vertices
    reduce_vertices
    check_for_nodes
    check_for_duplicates
    inp_to_graph
    get_path
    get_path_subgraph
    next_links
    next_links_labels
    next_nodes
    previous_links
    previous_links_labels
    previous_nodes
    links_connected
    number_in_out
    downstream_nodes
    upstream_nodes
    create_sub_inp
    split_network
    get_network_forks
    increase_max_node_depth
    set_times
    compare_sections
    compare_inp_files
    convert_inp_to_geo_package
    write_geo_package
    get_subcatchment_connectors
    problems_to_gis
    links_geo_data_frame
    nodes_geo_data_frame
    gpkg_to_swmm
    update_length

.. rubric:: check

.. automodule:: swmm_api.input_file.macros.check
    :members:
    :no-undoc-members:

.. rubric:: collection

.. automodule:: swmm_api.input_file.macros.collection
    :members:
    :no-undoc-members:

.. rubric:: compare

.. automodule:: swmm_api.input_file.macros.compare
    :members:
    :no-undoc-members:

.. rubric:: convert

.. automodule:: swmm_api.input_file.macros.convert
    :members:
    :no-undoc-members:

.. rubric:: curve

.. automodule:: swmm_api.input_file.macros.curve
    :members:
    :no-undoc-members:

.. rubric:: edit

.. automodule:: swmm_api.input_file.macros.edit
    :members:
    :no-undoc-members:

.. rubric:: filter

.. automodule:: swmm_api.input_file.macros.filter
    :members:
    :no-undoc-members:

.. rubric:: geo

.. automodule:: swmm_api.input_file.macros.geo
    :members:
    :no-undoc-members:

.. rubric:: gis

.. automodule:: swmm_api.input_file.macros.gis
    :members:
    :no-undoc-members:

.. rubric:: graph

.. automodule:: swmm_api.input_file.macros.graph
    :members:
    :no-undoc-members:

.. rubric:: macros

.. automodule:: swmm_api.input_file.macros.macros
    :members:
    :no-undoc-members:

.. rubric:: plotting

.. automodule:: swmm_api.input_file.macros.plotting
    :members:
    :no-undoc-members:

.. rubric:: reduce_unneeded

.. automodule:: swmm_api.input_file.macros.reduce_unneeded
    :members:
    :no-undoc-members:

.. rubric:: split_inp_file

.. automodule:: swmm_api.input_file.macros.split_inp_file
    :members:
    :no-undoc-members:

.. rubric:: tags

.. automodule:: swmm_api.input_file.macros.tags
    :members:
    :no-undoc-members:
