Input File Manipulation - GIS Macros
------------------------------------

.. currentmodule:: swmm_api.input_file.macros.gis

.. rubric:: Overview

.. autosummary::
    convert_inp_to_geo_package
    write_geo_package
    get_subcatchment_connectors
    problems_to_gis
    links_geo_data_frame
    nodes_geo_data_frame
    gpkg_to_swmm
    update_length


.. automodule:: swmm_api.input_file.macros.gis
    :members:
    :no-undoc-members:

