from swmm_api.input_file.section_labels import *

GEO_SECTIONS = [COORDINATES, VERTICES, POLYGONS]
GUI_SECTIONS = [MAP, SYMBOLS, LABELS, BACKDROP]
LINK_SECTIONS = [CONDUITS, ORIFICES, OUTLETS, PUMPS, WEIRS]
NODE_SECTIONS = [DIVIDERS, JUNCTIONS, OUTFALLS, STORAGE]
