Input File Manipulation-Macros
------------------------------

.. currentmodule:: swmm_api.input_file.inp_macros

.. rubric:: Overview

.. autosummary::
    section_from_frame
    split_inp_to_files
    combined_subcatchment_infos
    find_node
    find_link
    calc_slope
    delete_node
    combine_conduits
    conduit_iter_over_inp
    junction_to_storage
    junction_to_outfall
    remove_empty_sections
    reduce_curves
    reduce_raingages
    filter_nodes
    filter_links
    filter_subcatchments
