Input File Manipulation-Macros
------------------------------

.. currentmodule:: swmm_api.input_file.inp_macros

.. rubric:: Overview

.. autosummary::
    section_from_frame
    split_inp_to_files
    read_split_inp_file
    combined_subcatchment_frame
    nodes_dict
    find_node
    links_dict
    find_link
    calc_slope
    rel_diff
    conduits_are_equal
    delete_node
    delete_link
    combine_conduits
    conduit_iter_over_inp
    junction_to_storage
    junction_to_outfall
    conduit_to_orifice
    rename_node
    rename_link
    remove_empty_sections
    reduce_curves
    simplify_curves
    reduce_raingages
    filter_nodes
    filter_links_within_nodes
    filter_links
    filter_link_components
    filter_subcatchments
    group_edit
    update_vertices
    reduce_vertices
    check_for_nodes
    short_status
    inp_to_graph
    get_path
    next_links
    next_links_labels
    next_nodes
    previous_links
    previous_links_labels
    previous_nodes
    links_connected
    split_network

.. automodule:: swmm_api.input_file.inp_macros
    :members:
    :no-undoc-members:
