Input File Manipulation-Macros
------------------------------

.. currentmodule:: swmm_api.input_file.macro_snippets.gis_export

.. rubric:: Overview

.. autosummary::
    convert_inp_to_geo_package
    write_geo_package
    get_subcatchment_connectors
    problems_to_gis
    links_geo_data_frame
    nodes_geo_data_frame


.. automodule:: swmm_api.input_file.macro_snippets.gis_export
    :members:
    :no-undoc-members:
