Input File Manipulation - GIS Macros
------------------------------------

.. currentmodule:: swmm_api.input_file.macro_snippets.gis_export

.. rubric:: Overview

.. autosummary::
    convert_inp_to_geo_package
    write_geo_package
    get_subcatchment_connectors
    problems_to_gis
    links_geo_data_frame
    nodes_geo_data_frame


.. automodule:: swmm_api.input_file.macro_snippets.gis_export
    :members:
    :no-undoc-members:


.. currentmodule:: swmm_api.input_file.macro_snippets.gis_standard_import

.. rubric:: Overview

.. autosummary::
    gpkg_to_swmm


.. automodule:: swmm_api.input_file.macro_snippets.gis_standard_import
    :members:
    :no-undoc-members:
