Input File Manipulation - Macros
--------------------------------

.. currentmodule:: swmm_api.input_file.macros

.. rubric:: Overview

.. autosummary::
    section_from_frame
    split_inp_to_files
    read_split_inp_file
    combined_subcatchment_frame
    get_node_tags
    get_link_tags
    get_subcatchment_tags
    filter_tags
    nodes_dict
    find_node
    links_dict
    find_link
    calc_slope
    conduit_slopes
    conduits_are_equal
    delete_node
    move_flows
    delete_link
    delete_subcatchment
    split_conduit
    combine_vertices
    combine_conduits
    combine_conduits_keep_slope
    dissolve_conduit
    conduit_iter_over_inp
    junction_to_storage
    junction_to_outfall
    conduit_to_orifice
    subcachtment_nodes_dict
    rename_node
    rename_link
    rename_timeseries
    remove_empty_sections
    reduce_curves
    simplify_curves
    reduce_raingages
    filter_nodes
    filter_links_within_nodes
    filter_links
    filter_subcatchments
    group_edit
    update_vertices
    reduce_vertices
    check_for_nodes
    short_status
    inp_to_graph
    get_path
    get_path_subgraph
    next_links
    next_links_labels
    next_nodes
    previous_links
    previous_links_labels
    previous_nodes
    links_connected
    number_in_out
    downstream_nodes
    upstream_nodes
    create_sub_inp
    split_network
    get_network_forks
    increase_max_node_depth
    set_times
    compare_sections
    compare_inp_files

.. automodule:: swmm_api.input_file.macros
    :members:
    :no-undoc-members:

