Input File Reader
-----------------

.. currentmodule:: swmm_api.input_file.inp_reader

.. rubric:: Overview

.. autosummary::
    read_inp_file

.. automodule:: swmm_api.input_file.inp_reader
    :members:
    :no-undoc-members:


Input File Helpers
------------------

.. currentmodule:: swmm_api.input_file.inp_helpers

.. rubric:: Overview

.. autosummary::
    BaseSectionObject
    InpSectionGeneric
    InpSection
    InpData
    dataframe_to_inp_string

.. automodule:: swmm_api.input_file.inp_helpers
    :members:
    :no-undoc-members:
