# -*- coding: utf-8 -*-
#
# Configuration file for the Sphinx documentation builder.
#
# This file does only contain a selection of the most common options. For a
# full list see the documentation:
# http://www.sphinx-doc.org/en/master/config

# https://pydata-sphinx-theme.readthedocs.io/en/latest/index.html
# https://pydata-sphinx-theme.readthedocs.io/en/latest/demo/kitchen-sink/paragraph-markup.html
# https://raw.githubusercontent.com/pydata/pydata-sphinx-theme/master/docs/demo/kitchen-sink/paragraph-markup.rst
# pip install pydata-sphinx-theme
# https://docutils.sourceforge.io/docs/ref/rst/directives.html

# -- Path setup --------------------------------------------------------------

# If extensions (or modules to document with autodoc) are in another directory,
# add these directories to sys.path here. If the directory is relative to the
# documentation root, use os.path.abspath to make it absolute, like shown here.

import os
import sys
# from swmm_api import __version__

sys.path.insert(0, os.path.abspath('..'))
# print(*sys.path, sep='\n')

# -- Project information -----------------------------------------------------

project = 'swmm_api'
copyright = '2021, Pichler'
author = 'Pichler'
html_logo = "images/swmm_api_logo.svg"

# The short X.Y version
version = ''
# The full version, including alpha/beta/rc tags
release = '0.2.0.15'

html_theme_options = {  # https://fontawesome.com/v5.15/icons?d=gallery&p=2
    "icon_links": [
        {
            "name": "GitLab",
            "url": "https://gitlab.com/markuspichler/swmm_api",
            "icon": "fab fa-gitlab",
        },
        {
            "name": "PyPI",
            "url": "https://pypi.org/project/swmm-api/",
            "icon": 'fab fa-python',  # 'https://pypi.org/static/images/logo-small.95de8436.svg',
        },
        {
            "name": "SWW @ TU Graz",
            "url": "https://sww.tugraz.at",
            "icon": 'fas fa-tint',  # 'images/logo_sww.png',
        }
    ],
    "favicons": [
          {
             "rel": "icon",
             "sizes": "16x16",
             "href": 'images/swmm_api_logo_16.png',
          },
          {
             "rel": "icon",
             "sizes": "32x32",
             "href": 'images/swmm_api_logo_32.png',
          },
          {
             "rel": "apple-touch-icon",
             "sizes": "180x180",
             "href": 'images/swmm_api_logo_180.png'
          },
       ]
}

html_favicon = 'images/swmm_api_logo_16.png'

# -- General configuration ---------------------------------------------------

# If your documentation needs a minimal Sphinx version, state it here.
#
# needs_sphinx = '1.0'

# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom
# ones.
extensions = [
    'sphinx.ext.autodoc',
    'sphinx.ext.doctest',
    'sphinx.ext.intersphinx',
    'sphinx.ext.coverage',
    'sphinx.ext.mathjax',
    'sphinx.ext.viewcode',
    'sphinx.ext.githubpages',
    'sphinx.ext.autosummary',
    'sphinx.ext.extlinks',
    'sphinx.ext.napoleon',  # numpy/google docstrings
    'nbsphinx',  # jupyter notebook
    'recommonmark',  # markdown
]

# Add any paths that contain templates here, relative to this directory.
templates_path = ['_templates']

# The suffix(es) of source filenames.
# You can specify multiple suffix as a list of string:
#
# source_suffix = ['.rst', '.md']
# source_suffix = '.rst'

# source_suffix = {
#     '.rst': 'restructuredtext',
#     '.txt': 'markdown',
#     '.md': 'markdown',
# }

# The master toctree document.
master_doc = 'index'

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
#
# This is also used if you do content translation via gettext catalogs.
# Usually you set "language" from the command line for these cases.
language = None

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
# This pattern also affects html_static_path and html_extra_path.
exclude_patterns = ['public', 'Thumbs.db', '.DS_Store', '**.ipynb_checkpoints', '_build']

# The name of the Pygments (syntax highlighting) style to use.
# pygments_style = None


# -- Options for HTML output -------------------------------------------------

# The theme to use for HTML and HTML Help pages.  See the documentation for
# a list of builtin themes.
#
# html_theme = 'nature'
html_theme = 'pydata_sphinx_theme'  # 'sphinx_rtd_theme'
# html_theme = 'alabaster'

# Theme options are theme-specific and customize the look and feel of a theme
# further.  For a list of options available for each theme, see the
# documentation.
#
# html_theme_options = {}

# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".
html_static_path = ['_static']

html_css_files = [
    'css/custom.css',
]

# Custom sidebar templates, must be a dictionary that maps document names
# to template names.
#
# The default sidebars (for documents that don't match any pattern) are
# defined by theme itself.  Builtin themes are using these templates by
# default: ``['localtoc.html', 'relations.html', 'sourcelink.html',
# 'searchbox.html']``.
#
# html_sidebars = {}


# -- Options for HTMLHelp output ---------------------------------------------

# Output file base name for HTML help builder.
htmlhelp_basename = 'swmm_api'


# -- Options for LaTeX output ------------------------------------------------

latex_elements = {
    # The paper size ('letterpaper' or 'a4paper').
    #
    # 'papersize': 'letterpaper',

    # The font size ('10pt', '11pt' or '12pt').
    #
    # 'pointsize': '10pt',

    # Additional stuff for the LaTeX preamble.
    #
    # 'preamble': '',

    # Latex figure (float) alignment
    #
    # 'figure_align': 'htbp',
}

# Grouping the document tree into LaTeX files. List of tuples
# (source start file, target name, title,
#  author, documentclass [howto, manual, or own class]).
#latex_documents = [
#    (master_doc, 'IntensityDurationFrequencyAnalyse.tex', 'Intensity Duration Frequency Analyse Documentation',
#     'Pichler', 'manual'),
#]


# -- Options for manual page output ------------------------------------------

# One entry per manual page. List of tuples
# (source start file, name, description, authors, manual section).
man_pages = [
    (master_doc, 'swmm_api', 'EPA-SWMM API Documentation',
     [author], 1)
]


# -- Options for Texinfo output ----------------------------------------------

# Grouping the document tree into Texinfo files. List of tuples
# (source start file, target name, title, author,
#  dir menu entry, description, category)
texinfo_documents = [
    (master_doc, 'SWMM_API', 'SWMM API Documentation',
     author, 'SWMM_API', 'One line description of project.',
     'Miscellaneous'),
]


# -- Options for Epub output -------------------------------------------------

# Bibliographic Dublin Core info.
epub_title = project

# The unique identifier of the text. This can be a ISBN number
# or the project homepage.
#
# epub_identifier = ''

# A unique identification for the text.
#
# epub_uid = ''

# A list of files that should not be packed into the epub file.
epub_exclude_files = ['search.html']


# -- Extension configuration -------------------------------------------------

# -- Options for intersphinx extension ---------------------------------------

# Example configuration for intersphinx: refer to the Python standard library.
intersphinx_mapping = {'https://docs.python.org/3/': None,
                       # 'pd': ('http://pandas.pydata.org/pandas-docs/stable/', None),
                       'https://pandas.pydata.org/pandas-docs/stable/': None,
                       'numpy': ('https://numpy.org/doc/stable/', None),
                       # 'scipy': ('http://docs.scipy.org/doc/scipy/reference/', None),
                       # 'matplotlib': ('http://matplotlib.sourceforge.net/', None),
                       # 'sympy': ('https://docs.sympy.org/latest/', None),
                       'sympy': ('https://docs.sympy.org/latest/', 'https://docs.sympy.org/latest/objects.inv'),
                       'networkx': ('https://networkx.org/documentation/stable/', 'https://networkx.org/documentation/stable/objects.inv'),
                       'pyproj': ('https://pyproj4.github.io/pyproj/stable/', None)
                       }
